import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { CiscoIOSGeneratedModule, CiscoIosGeneratedSharedModule } from './generated/module.js';
import { CiscoIosValidator, registerValidationChecks } from './cisco-ios-validator.js';
import { CiscoIosScopeProvider } from './cisco-ios-scopeProvider.js';
import { CiscoIosCompletionProvider } from './cisco-ios-completionProvider.js';
import { CiscoIosLinker } from './cisco-ios-linker.js';
import { CiscoIosSemanticTokenProvider } from './cisco-ios-semanticTokenProvider.js';
/**
 * Declaration of custom services - add your own service classes here.
 */
export type CiscoIosAddedServices = {
    validation: {
        CiscoIosValidator: CiscoIosValidator
    },
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type CiscoIosServices = LangiumServices & CiscoIosAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const CiscoIosModule: Module<CiscoIosServices, PartialLangiumServices & CiscoIosAddedServices> = {
    validation: {
        CiscoIosValidator: () => new CiscoIosValidator()
    },

    references: {
        ScopeProvider: (services) => new CiscoIosScopeProvider(services),
        Linker: (services) => new CiscoIosLinker(services),
    },
    lsp: {
        CompletionProvider: (services) => new CiscoIosCompletionProvider(services),
        SemanticTokenProvider: (services) => new CiscoIosSemanticTokenProvider(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createCiscoIosServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    CiscoIos: CiscoIosServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        CiscoIosGeneratedSharedModule
    );
    const CiscoIos = inject(
        createDefaultModule({ shared }),
        CiscoIOSGeneratedModule,
        CiscoIosModule,
    );
    shared.ServiceRegistry.register(CiscoIos);
    registerValidationChecks(CiscoIos);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, CiscoIos };
}

